version: 2

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: lu
    main: ./cmd/lu
    binary: lu
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/ipanardian/lu-hut/internal/constants.Version={{.Version}}

archives:
  - id: lu-archive
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - Merge pull request
      - Merge branch

brews:
  - name: lu-hut
    ids:
      - lu-archive
    repository:
      owner: ipanardian
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Formula
    homepage: https://github.com/ipanardian/lu-hut
    description: "A powerful modern alternative to the Unix ls command"
    license: GPL-3.0
    install: |
      bin.install "lu"
    test: |
      system "#{bin}/lu", "version"
